version: '3.8'

services:
  fe:
    build:
      context: .
      dockerfile: Dockerfile.fe
    container_name: frontend
    restart: unless-stopped
    environment:
      APP_NAME: ${APP_NAME}
      APP_ENV: ${APP_ENV}
      APP_KEY: ${APP_KEY}
      APP_DEBUG: ${APP_DEBUG}
      APP_URL: ${APP_URL}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      MQTT_HOST: ${MQTT_HOST}
      MQTT_PORT: ${MQTT_PORT}
      MQTT_CLIENT_ID: ${MQTT_CLIENT_ID}
      MQTT_CLEAN_SESSION: ${MQTT_CLEAN_SESSION}
      MQTT_ENABLE_LOGGING: ${MQTT_ENABLE_LOGGING}
      MQTT_AUTH_USERNAME: ${MQTT_AUTH_USERNAME}
      MQTT_AUTH_PASSWORD: ${MQTT_AUTH_PASSWORD}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    volumes:
      - .:/var/www
    networks:
      - app-network
    depends_on:
      - be
      - db

  be:
    build:
      context: .
      dockerfile: Dockerfile.be
    container_name: backend
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "6380:6379"
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    volumes:
      - ./:/var/www
      - ./netprofe:/var/www/html/netpro
      - ./public:/var/www/public
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
    networks:
      - app-network

  db:
    image: mysql:5.7
    container_name: db
    restart: unless-stopped
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_DATABASE: ${DB_DATABASE}
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-network
    ports:
      - "3306:3306"

volumes:
  dbdata:

networks:
  app-network:
    name: app-network
    driver: bridge
